# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
