# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171029_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntateacher',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
