# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170913_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuntaaccesstoken',
            name='application',
        ),
        migrations.RemoveField(
            model_name='appuntaaccesstoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppuntaAccessToken',
        ),
    ]
