# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20170913_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppuntaAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appunta_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
