# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_guide_primitive'),
        ('users', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Guide')),
            ],
        ),
    ]
