# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_courselink'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.TextField(default='curse title!', max_length=128),
            preserve_default=False,
        ),
    ]
