# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171012_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselink',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinks', to='users.Course'),
        ),
    ]
