# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='area',
            new_name='field_of_study',
        ),
    ]
