# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='material.Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='sub_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='material.SubUnit'),
        ),
        migrations.AlterField(
            model_name='feedbackcomment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to='material.Content'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunits', to='material.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='material.FieldOfStudy'),
        ),
    ]
