# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20170807_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='material.Unit'),
        ),
    ]
