# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselink',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Guide'),
        ),
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(to='users.AppuntaStudent'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AppuntaTeacher'),
        ),
    ]
