# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171029_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(related_name='courses', to='users.AppuntaStudent'),
        ),
    ]
