# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171029_1601'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='course',
        ),
        migrations.AddField(
            model_name='guide',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
        migrations.AddField(
            model_name='guide',
            name='private',
            field=models.IntegerField(default=0),
        ),
    ]
