# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20171029_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='courses',
        ),
    ]
