# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20170807_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='content',
            name='sub_unit',
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle',
            field=models.CharField(default='Handy subtitle', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='material.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='academic_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubUnit',
        ),
    ]
