# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_remove_guide_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='html_text',
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(validators=[material.models.validate_entries]),
        ),
    ]
