# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_content_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=material.models.generate_thumbnail_path),
        ),
    ]
