# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20171030_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='subtitle',
            new_name='title',
        ),
    ]
