# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20170815_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldOfStudy',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='field_of_study',
            new_name='subject',
        ),
    ]
