# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171029_1618'),
        ('material', '0006_auto_20171030_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='user',
        ),
        migrations.AddField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='users.AppuntaTeacher'),
            preserve_default=False,
        ),
    ]
