# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20171101_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
