# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20170912_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
    ]
