# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20170914_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.URLField(blank=True, default=''),
        ),
    ]
