# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_guide_guideitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideitem',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='guideitem',
            old_name='excercise',
            new_name='exercise',
        ),
        migrations.AlterUniqueTogether(
            name='guideitem',
            unique_together=set([('guide', 'order')]),
        ),
    ]
