# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course'),
        ('material', '0013_auto_20170914_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
        ),
    ]
