# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_content_primitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideitem',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='material.Guide'),
        ),
    ]
