# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0016_auto_20171011_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='primitive',
            field=models.TextField(blank=True),
        ),
    ]
