# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_guide_primitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='feedbackcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
