# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_auto_20171012_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL),
        ),
    ]
