# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_auto_20171012_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedbackcomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
