# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0019_auto_20171012_0041'),
        ('material', '0019_auto_20171012_0323'),
    ]

    operations = [
    ]
