# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexercise',
            name='briefing',
            field=models.TextField(blank=True, default=''),
        ),
    ]
