# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_automatedexercise_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedexerciseanswer',
            name='moment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automatedexerciseanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
