# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_auto_20170912_2233'),
        ('exercises', '0002_auto_20170911_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedexercise',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='material.Unit'),
            preserve_default=False,
        ),
    ]
