# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_automatedexerciseanswer_tscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automatedexerciseanswer',
            unique_together=set([]),
        ),
    ]
