# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_automatedexercise_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexercise',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Teacher'),
        ),
    ]
