# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20171029_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedexercise',
            name='text',
            field=models.TextField(default='', validators=[exercises.models.validate_exercise]),
            preserve_default=False,
        ),
    ]
