# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170913_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexercise',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Teacher'),
            preserve_default=False,
        ),
    ]
