# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

"""
This kind of crap is the reason our specie is a failure and it makes me angry!
"""

def set_my_defaults(apps, schema_editor):
    AutomatedExerciseAnswer = apps.get_model('exercises', 'AutomatedExerciseAnswer')
    for series in AutomatedExerciseAnswer.objects.all().iterator():
        series.student = series.user.student
        series.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171029_1618'),
        ('exercises', '0006_automatedexercise_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedexerciseanswer',
            name='student',
            field= models.ForeignKey(null=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.AppuntaStudent'),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults),
        migrations.AlterField(
            model_name='automatedexerciseanswer',
            name='student',
            field= models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.AppuntaStudent'),
        ),
        migrations.RemoveField(
            model_name='automatedexerciseanswer',
            name='user',
        ),
    ]
