# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_automatedexercise_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexercise',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='users.Teacher'),
        ),
        migrations.AlterField(
            model_name='automatedexercise',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='material.Unit'),
        ),
    ]
