# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20171101_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexerciseanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.AppuntaStudent'),
        ),
    ]
