# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_automatedexercise_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automatedexercise',
            old_name='original',
            new_name='update',
        ),
    ]
