# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_auto_20171010_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedexercise',
            name='primitive',
            field=models.TextField(blank=True),
        ),
    ]
