# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_automatedexercise_primitive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedexercise',
            name='update',
        ),
    ]
