# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0011_remove_automatedexercise_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exercises.AutomatedExercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
