# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0011_remove_automatedexercise_update'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automatedexerciseanswer',
            unique_together=set([('user', 'exercise')]),
        ),
    ]
