# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_exercisecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 2, 8, 22, 310647)),
        ),
    ]
